sentinel2:
      filename: S2A_MSIL1C_20200824T110631_N0209_R137_T30UXD_20200824T150432.SAFE
      directory: /gws/nopw/j04/qa4ecv_vol2/HR_Alebdo/WheatBelt/30UXD/30UXD
      tile: 30UXD

MODIS:
      tile: h17v03

EEA:
      SampleInterval: 10
      PatchSize: 1000
      Overlap: 50
